credentials:
  batch:
    account_key: Zjkw1BBZ5duQ9vI6NuCHimyBhRbFlMEx67Y0XXPvyiL6O/vZQe+RPWV6mGyxyi4chc2yZmaMadY08hh3kosE3A==
    account_service_url: https://cjoakimbatch2.eastus.batch.azure.com
  storage:
    cjoakimstdstorage:
      account: cjoakimstdstorage
      account_key: 7SPUdEMEMV185ZY/JDlCvybizujNLGoGqR9U5sKYcO3RTS60lo9lEvXdgk7U0DeILYlTQdk/6bBHsT6WM5E4Fw==
      endpoint: core.windows.net
