credentials:
  batch:
    account_key: h635L8tFPgrHfdU0JalSB+KUn3QWPShYUxZ9cRviy/fCWzAQDSHcjU9WIX6Bupl4Zhfj1O0lf50531f+lIwBIQ==
    account_service_url: https://cjoakimbatch1.eastus.batch.azure.com
  storage:
    cjoakimstdstorage:
      account: cjoakimstdstorage
      account_key: 7SPUdEMEMV185ZY/JDlCvybizujNLGoGqR9U5sKYcO3RTS60lo9lEvXdgk7U0DeILYlTQdk/6bBHsT6WM5E4Fw==
      endpoint: core.windows.net
