credentials:
  batch:
    account_key: <secret>
    account_service_url: https://cjoakimbatch2.eastus.batch.azure.com
  storage:
    cjoakimstdstorage:
      account: cjoakimstdstorage
      account_key: <secret>
      endpoint: core.windows.net
