job_specifications:
- id: cjoakimshipyard1
  environment_variables:
    AZURE_STORAGE_ACCOUNT: cjoakimstdstorage
    AZURE_STORAGE_KEY: <secret>
  tasks:
  - docker_image: cjoakim/azure-batch-shipyard1:latest
    command: env | sort ; docker run -d -e AZURE_STORAGE_ACCOUNT=$AZURE_STORAGE_ACCOUNT -e AZURE_STORAGE_KEY=$AZURE_STORAGE_KEY cjoakim/azure-batch-shipyard1:latest
    remove_container_after_exit: true
