pool_specification:
  id: cjoakimpool2
  vm_size: Standard_DS3_v2
  vm_count:
    dedicated: 1
    low_priority: 0
  vm_configuration:
    platform_image:
      publisher: Canonical
      offer: UbuntuServer
      sku: 16.04-LTS
  reboot_on_start_task_failed: false
  block_until_all_global_resources_loaded: true
